name: Build APK and EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-apk:
    name: Build Android APK with EAS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
      - run: eas build --platform android --non-interactive --profile preview
        env:
          EAS_ACCESS_TOKEN: ${{ secrets.EAS_ACCESS_TOKEN }}

  build-exe:
    name: Build Windows EXE with Electron
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - run: npm run build:web
      - run: npx electron-builder --win
